### ISSUE TITLE
Support for react-native 0.56

### ISSUE THREAD

**Issue by yenda** [status-im/clj-rn#13]
To work with react-native 0.56, the require for figwheel bridge needs to be `./figwheel-bridge` instead of `figwheel-bridge` which requires a change here https://github.com/status-im/clj-rn/blob/master/src/clj_rn/core.clj#L135

see https://github.com/drapanjanas/re-natal/issues/189

**Comment by dmitryn** [comment]
@yenda changing `:figwheel-bridge` option in `clj-rn.conf.edn` to
```
:figwheel-bridge "./figwheel-bridge.js"
``` 
works for me.
