### ISSUE TITLE
Do not require local figwheel-bridge.js

### ISSUE THREAD

**Issue by jeluard** [status-im/clj-rn#2]
In order to hook RN with figwheel `re-natal` introduces a local `figwheel-bridge.js` file.

 Make sure that this file is not required locally. It should still be possible to make local adaptation, if relevant.

It might be worth looking into how clojurescript [handles](https://github.com/clojure/clojurescript/blob/27c27e0b53f6ef550670d7aed981395a96aae1da/src/main/clojure/cljs/closure.clj#L1674) different targets (nodejs, webworker).

**Comment by status-open-bounty** [comment]
Balance: 0 ETH
Tokens: SNT: 5000.00
Contract address: [0x23d4198ef3334c69a5d43088593dba3fb349684c](https://etherscan.io/address/0x23d4198ef3334c69a5d43088593dba3fb349684c)
Network: Mainnet
Paid to: psdp
Visit [https://openbounty.status.im](https://openbounty.status.im) to learn more.
