### ISSUE TITLE
Create a dashboard to monitor logs

### ISSUE THREAD

**Issue by jeluard** [status-im/clj-rn#4]
Both figwheel and the running app generates logs. Makes it easy to browse those logs in realtime.

Some links:

* https://github.com/facebook/react-native/tree/master/local-cli/logAndroid
* https://github.com/facebook/react-native/tree/master/local-cli/logIOS

**Comment by status-open-bounty** [comment]
![Contract deploying](https://openbounty.status.im/img/deploying_contract.png)
Transaction: [0x12e5892bd1ec91652c62a978bb24a1b46ed3ec11ebaf1b3247ccdfbcb2a1d948](https://etherscan.io/tx/0x12e5892bd1ec91652c62a978bb24a1b46ed3ec11ebaf1b3247ccdfbcb2a1d948)

**Comment by tao** [comment]
Would you be able to facebooks new debugging tool [sonar](https://fbsonar.com) - it supports logs... if it can work with the figwheel?

**Comment by jeluard** [comment]
I was more thinking about a CLI based tool.
