### ISSUE TITLE
Add desktop platform along with ios and android

### ISSUE THREAD

**Issue by vkjr** [status-im/clj-rn#8]
In `status-react` we use also `react-native-desktop` to have a desktop implementation of the app.
So, `desktop` platform need to be added to `clj-rn` and `index.desktop.js` should be generated.

**Comment by jeluard** [comment]
@endenwer Given your recent work, do you have any thoughts on this? Same question for #9 :D

**Comment by endenwer** [comment]
@jeluard I didn't find how to build status for desktop but if it is already working it is not a problem to add it. Although it seems that re-natal fork does not have desktop support yet https://github.com/status-im/re-natal/blob/master/re-natal.coffee#L497 so it can take some time to implement it here.
Issue #9 is simpler, only need to change `rebuild-index` task if it will be without `host` option as in re-natal.

**Comment by vkjr** [comment]
@endenwer, If I understand correctly, the line you are pointing to is about generating project from scratch?
We don't need this functionality of re-natal for desktop build. Basically all we need is to have `index.desktop.js` generated. Fork of re-natal now has this functionality and when we do `./re-natal use-figwheel`, we are getting that file along with `index.ios.js` and `index.android.js`.

**Comment by endenwer** [comment]
@vkjr Looks like the only difference `index.desktop.js` from `index.ios.js` and `index.android.js` is the name(and the modules after #9 is implemented). If so then generations of the file is the same and only need to add ability to pass `desktop` as build and change some functions a little bit.

**Comment by vkjr** [comment]
@endenwer, great!
