### ISSUE TITLE
Support platform-dependent modules list in clj-rn.conf.edn

### ISSUE THREAD

**Issue by vkjr** [status-im/clj-rn#9]
In `.re-natal` it is possible to list platform-dependent modules to be included in `index.platform.js` with following syntax: 

```
"platforms": {
    "ios": {
      "host": "localhost",
      "modules": [
        "react-native-image-resizer",
        "react-native-camera",
        "instabug-reactnative",
        "nfc-react-native",
        "react-native-background-timer",
        "react-native-testfairy"
      ]
    },
```
We use this feature to provide different list of modules for mobile and desktop platforms in `status-react`.

@jeluard, is the same functionality exists in `clj-rn-conf.edn` or need to be implemented?
Thanks!

**Comment by yenda** [comment]
@dmitryn can this be closed ?

**Comment by dmitryn** [comment]
@yenda yes, i supposed it will auto-close with PR merged.
